### PR TITLE
Update backport package namespace

### PR DESCRIPTION
**Pull request by wizmer**
This is a cherry-pick from the NixOS official repo
It fixes an import error:

from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

### CODE REVIEW

**Comment by wizmer** [comment]
It might also fix the collision problem which was related to the same namespace package

**Comment by wizmer** [comment]
Can we merge this ? :)

**Comment by wizmer** [comment]
@ppodhajski Here is what should be resolved after the following PR:
```
nix-shell -p bluepymm
python -c "import bluepymm"
```

**Comment by ppodhajski** [comment]
`nix-build -A modules.all
 `

collision between `/nix/store/wy4akip12g7c9af0z9qpilgs47p7cvqp-python2.7-backports.functools_lru_cache-1.5/lib/python2.7/site-packages/backports/__init__.py' and `/nix/store/r0mrppmx70m61blgawa9v8va2j1zs3pp-python2.7-backports.ssl_match_hostname-3.5.0.1/lib/python2.7/site-packages/backports/__init__.py'

**Comment by ppodhajski** [comment]
It does resolve the problem. on the other hand "ignoreCollisions=true" option will have to be added to scikit-* modules, which is I guess OK

**Comment by wizmer** [comment]
Ok, let me try to fix that.

**Pull request merged**
